defmodule RewovenCurriculum.Lessons do
  @moduledoc """
  Placeholder — the real lesson content is being generated by an agent
  and will replace this file once written. This stub returns nil for any
  lesson lookup so the lesson template falls back to "Coming soon."
  """
  def content(_course_slug, _lesson_slug), do: nil
end
